<a href="https://colab.research.google.com/github/yoonputer/test_python/blob/master/python_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
def onehotcylinder(cylinders):
  if cylinders == 3:
    cylinder = np.array([1,0,0,0,0])
  elif cylinders == 4:
    cylinder = np.array([0,1,0,0,0])
  elif cylinders == 5:
    cylinder = np.array([0,0,1,0,0])
  elif cylinders == 6:
    cylinder = np.array([0,0,0,1,0])
  elif cylinders == 8:
    cylinder = np.array([0,0,0,0,1])
  return cylinder

In [3]:
displacement = 307.0
horsepower = 130.0
weight = 3504.0
accel = 12.0
cylinders = 8
origin = 1

## if cylinders = 8, origin = 1 --> onehot encoding
import numpy as np

x_continus = np.array([displacement, horsepower, weight, accel])
# cylinder = np.array([0,0,0,0,1]) # 8
cylinder = onehotcylinder(cylinders)
org = np.array([1,0,0]) # 1

In [4]:
#np.concatenate((a, b), axis=None)
result = np.concatenate((x_continus, cylinder, org), axis=None)
result.shape, result

((12,),
 array([3.070e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00]))

In [5]:
#[307.0,130.0,3504.0,12.0, 0,0,0,0,1]
# result.reshape(1,12)      # 하드 코딩 (바꾸기 어려움) ex) 1+3 = 4
result = result.reshape(-1, result.size)  # 소프트 코딩 ex) x=1, y=3  x+y 
result, result.shape, result.size,

(array([[3.070e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
         0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00]]),
 (1, 12),
 12)

------

------

In [6]:
onehotcylinder(4), onehotcylinder(6)

(array([0, 1, 0, 0, 0]), array([0, 0, 0, 1, 0]))

In [7]:
cylinder

array([0, 0, 0, 0, 1])

In [8]:
type(x_continus), type(cylinder), type(org)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

# function 이해

In [9]:
21 + 14

35

In [10]:
32 + 45

77

In [11]:
def sum():
  first = 32
  second = 45
  resultt = first + second
  return resultt

In [12]:
sum()

77

In [13]:
def sum(f,s):
  first = f
  second = s
  resultt = first + second
  return resultt, first, second

In [14]:
r01, r02, r03 = sum(21,564)
print(r01,r02)

585 21


In [15]:
#def differenceVars(*var01, **args02)
def diffparam(*var_list, **var_dict):
  print(var_dict)
  result01 = len(var_list)
  return result01

In [16]:
diffparam(1,2,3, a=2,b=3)

{'a': 2, 'b': 3}


3

In [17]:
diffparam(1,2,3,5,6, c=5, d=6, a=2,b=3)

{'c': 5, 'd': 6, 'a': 2, 'b': 3}


5

In [18]:
def gob(a,b,c):
  first = a
  second = b
  third = c
  result = first * second * third
  return result

In [19]:
gob(21,32,2), gob(31,63,41)

(1344, 80073)